"""Confidence the platform computed — MerchantOps v2 §33.

`incidents.confidence_band` is the band derived from the evidence;
`confidence_inputs` is the derivation, kept so "why HIGH?" has an answer.
Distinct from `agent_tasks.agent_confidence`, which stays what it was: the
number the model chose for itself, now an input that can only lower this band.
See app/agent/confidence.py and ADR-0034.

Revision ID: 282341769486
Revises: b62fab502d7d
Created: 2026-09-01 23:25:14.696311
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '282341769486'
down_revision = 'b62fab502d7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # `confidence_band` is nullable because an incident detected before this
    # migration was never assessed, and back-filling it with a value would be
    # inventing a view nobody formed. Null means "not assessed" and the API
    # renders it as absent rather than as a band.
    op.add_column('incidents',
                  sa.Column('confidence_band', sa.String(length=16), nullable=True))

    # `confidence_inputs` is NOT NULL, so it needs a server_default to be
    # addable to a table that already has rows -- autogenerate emits the column
    # without one, which works against the empty database it compared and fails
    # against every database that matters. The default is dropped immediately:
    # it exists to fill existing rows, not to become part of the schema.
    op.add_column('incidents',
                  sa.Column('confidence_inputs', sa.JSON(), nullable=False,
                            server_default=sa.text("'{}'::json")))
    op.alter_column('incidents', 'confidence_inputs', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'confidence_inputs')
    op.drop_column('incidents', 'confidence_band')
    # ### end Alembic commands ###
