"""campaign risk bound

Revision ID: 0f0125d98b5a
Revises: 39bcb244faa1
Created: 2026-09-02 01:15:33.706078
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0f0125d98b5a'
down_revision = '39bcb244faa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL, so it needs a server_default to be addable to a table that
    # already holds plans. Autogenerate emits it without one, which works
    # against the empty database it compared and fails against every database
    # that matters. 'HIGH' is what `MAX_UNATTENDED_RISK` enforced globally
    # before this column existed, so an in-flight plan keeps exactly the bound
    # it was already running under. The default is dropped immediately: it is
    # here to back-fill, not to become part of the schema.
    op.add_column('recovery_plans',
                  sa.Column('max_risk_level', sa.String(length=16),
                            nullable=False, server_default='HIGH'))
    op.alter_column('recovery_plans', 'max_risk_level', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_plans', 'max_risk_level')
    # ### end Alembic commands ###
