"""hypotheses

Revision ID: 39bcb244faa1
Revises: 8074e10d90fc
Created: 2026-09-02 01:03:41.432554
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '39bcb244faa1'
down_revision = '8074e10d90fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUPPORTED', 'CONTENDING', 'REJECTED', 'UNTESTED', name='hypothesisstatus', native_enum=False), nullable=False),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adjudicated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'key', name='uq_hypothesis_once')
    )
    op.create_index(op.f('ix_hypotheses_incident_id'), 'hypotheses', ['incident_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_key'), 'hypotheses', ['key'], unique=False)
    op.create_index(op.f('ix_hypotheses_merchant_id'), 'hypotheses', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_hypotheses_tenant_id'), 'hypotheses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypotheses_tenant_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_merchant_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_key'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_incident_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
