"""operator notifications

The table behind `app/notify` -- one row per (notification, recipient,
channel), written before the send is attempted so a process killed mid-send
leaves evidence rather than a gap.

`uq_notification_once` on `dedupe_key` is the load-bearing part. The approval
sweep recomputes "expiring soon" on every pass over a fifteen-minute window, so
without it a chase would be re-sent on every cadence. Enforced by the database
rather than by a preceding SELECT because two drains can run concurrently and
because a retry must not become a second email.

LOCKING: `CREATE TABLE` on a table nothing references yet. No rewrite, no lock
on anything in use.

A NOTE ON GENERATING THIS ONE, because it wastes an hour otherwise:
autogenerate compares the models to the database, and `scripts/seed_data.py`
builds the schema with `create_all` from those same models. Run seed and then
autogenerate and you get an empty migration -- the table is already there.
Generate against a database brought to the *previous* head by migrations alone.

Revision ID: 351d7cd7c50d
Revises: d09395a87106
Created: 2026-09-05 00:19:02.440855
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '351d7cd7c50d'
down_revision = 'd09395a87106'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('APPROVAL_REQUESTED', 'APPROVAL_EXPIRING', 'APPROVAL_EXPIRED', 'INCIDENT_OPENED', 'ACTION_ESCALATED', 'VERIFICATION_UNKNOWN', name='notificationkind', native_enum=False), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SUPPRESSED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_once')
    )
    op.create_index(op.f('ix_operator_notifications_correlation_id'), 'operator_notifications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_operator_notifications_merchant_id'), 'operator_notifications', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_operator_notifications_status'), 'operator_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_operator_notifications_subject_id'), 'operator_notifications', ['subject_id'], unique=False)
    op.create_index(op.f('ix_operator_notifications_tenant_id'), 'operator_notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_notifications_tenant_id'), table_name='operator_notifications')
    op.drop_index(op.f('ix_operator_notifications_subject_id'), table_name='operator_notifications')
    op.drop_index(op.f('ix_operator_notifications_status'), table_name='operator_notifications')
    op.drop_index(op.f('ix_operator_notifications_merchant_id'), table_name='operator_notifications')
    op.drop_index(op.f('ix_operator_notifications_correlation_id'), table_name='operator_notifications')
    op.drop_table('operator_notifications')
    # ### end Alembic commands ###
