"""queued tasks and worker heartbeats

Asynchronous task execution (ADR-0045): a task can be accepted now and run by a
worker later, and `worker_heartbeats` is how the absence of a worker becomes
visible instead of looking like an absence of work.

`model_version` and `prompt_version` become NULLABLE. They are §41 provenance --
what actually ran -- and a QUEUED task has not run. Writing them at enqueue
would record a prediction where a measurement belongs, and the provider can
genuinely change in between (`POST /config/llm-provider`). Widening a column to
nullable is backward compatible: every existing row keeps its value.

LOCKING: `ADD COLUMN` with a constant default and `ALTER COLUMN ... DROP NOT
NULL` are both metadata-only on PostgreSQL 11+ -- no table rewrite. The partial
index is built without CONCURRENTLY, which takes a brief ACCESS EXCLUSIVE lock;
on a table of any size, build it concurrently outside a transaction instead.

Revision ID: dcb6f90706de
Revises: 351d7cd7c50d
Created: 2026-09-05 01:18:33.130416
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'dcb6f90706de'
down_revision = '351d7cd7c50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jobs', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_heartbeats_last_seen_at'), 'worker_heartbeats', ['last_seen_at'], unique=False)
    op.add_column('agent_tasks', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_tasks', sa.Column('claimed_by', sa.String(length=64), nullable=True))
    op.add_column('agent_tasks', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # server_default, or this fails on any table that already has rows: a NOT
    # NULL column added with no default has nothing to put in them. The default
    # stays on the column rather than being dropped afterwards -- it is the
    # right value for a row that has never been claimed, and removing it would
    # make the application responsible for a zero the database can supply.
    op.add_column('agent_tasks', sa.Column(
        'attempts', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('agent_tasks', 'model_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('agent_tasks', 'prompt_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###

    # The claim query orders queued tasks by age and takes one. Without this it
    # is a sequential scan of every task ever run, on the hottest path the
    # worker has -- every two seconds, forever. Partial, because only QUEUED
    # rows are ever selected this way and the index should not carry the
    # millions that are not.
    op.create_index(
        "ix_agent_tasks_queued", "agent_tasks", ["queued_at", "id"],
        postgresql_where=sa.text("status = 'QUEUED'"))
    # Abandoned-claim recovery scans RUNNING rows by lease age.
    op.create_index(
        "ix_agent_tasks_claimed", "agent_tasks", ["claimed_at"],
        postgresql_where=sa.text("status = 'RUNNING'"))


def downgrade() -> None:
    op.drop_index("ix_agent_tasks_claimed", table_name="agent_tasks")
    op.drop_index("ix_agent_tasks_queued", table_name="agent_tasks")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tasks', 'prompt_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('agent_tasks', 'model_version',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('agent_tasks', 'attempts')
    op.drop_column('agent_tasks', 'claimed_at')
    op.drop_column('agent_tasks', 'claimed_by')
    op.drop_column('agent_tasks', 'started_at')
    op.drop_column('agent_tasks', 'queued_at')
    op.drop_index(op.f('ix_worker_heartbeats_last_seen_at'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
