"""The transactional outbox — MerchantOps v2 §12.

One table, written inside whatever transaction produced the business state it
describes, drained afterwards by `app.events.bus.drain`. See ADR-0033.

`ix_outbox_drain` on (status, occurred_at) is the one the drain uses; the
single-column indexes serve the read path (`EventStore.since`) and the
correlation join that ties a stream frame back to its audit trail.

Revision ID: b62fab502d7d
Revises: a1c47f9b2e08
Created: 2026-09-01 23:05:06.062483
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b62fab502d7d'
down_revision = 'a1c47f9b2e08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'DEAD', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_correlation_id'), 'event_outbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_entity_id'), 'event_outbox', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_incident_id'), 'event_outbox', ['incident_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_merchant_id'), 'event_outbox', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_occurred_at'), 'event_outbox', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_status'), 'event_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_event_outbox_task_id'), 'event_outbox', ['task_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_tenant_id'), 'event_outbox', ['tenant_id'], unique=False)
    op.create_index('ix_outbox_drain', 'event_outbox', ['status', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_drain', table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_tenant_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_task_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_status'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_occurred_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_merchant_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_incident_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_entity_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_correlation_id'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
