"""money is bigint

Widens every monetary column from integer to bigint.

PostgreSQL's `integer` tops out at 2,147,483,647, which in paise is about
₹21.47 million. On a single payment that ceiling is arguable; on the
aggregates it is not. `revenue_at_risk_minor` and the recovery totals
accumulate across every affected transaction in an incident, and PostgreSQL
raises `integer out of range` rather than wrapping -- so the failure lands as
a 500 on the dashboard at the moment the incident being measured is at its
worst.

OPERATIONAL COST -- read before running this on a live database.

An integer-to-bigint change rewrites the table and holds ACCESS EXCLUSIVE for
the duration: no reads, no writes, for as long as the rewrite takes. On the
volumes this system carries (hundreds of payments) that is milliseconds. On a
real merchant's history it is not, and the tables here are the ones that grow
fastest -- `payments`, `orders`, `refunds`, `recovery_candidates`.

At a size where that matters, do not run this as-is. The zero-downtime shape is
per column: ADD a new bigint column, backfill in batches, sync with a trigger,
then swap in a transaction. That is deliberately not automated here -- it needs
a decision per table about batch size and window, and ADR-0030 keeps every
migration in this repository transactional and reviewable rather than clever.

Revision ID: d09395a87106
Revises: ef2c7d9613d9
Created: 2026-09-04 01:53:49.323977
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd09395a87106'
down_revision = 'ef2c7d9613d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_actions', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('incidents', 'revenue_at_risk_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('orders', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_links', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'amount_refunded_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('products', 'price_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'attributed_amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'expected_recovery_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'actual_recovery_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'revenue_at_risk_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'eligible_recovery_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'expected_recovery_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'max_recovery_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('refunds', 'amount_minor',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'max_recovery_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'expected_recovery_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'eligible_recovery_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_plans', 'revenue_at_risk_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'actual_recovery_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'expected_recovery_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'attributed_amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recovery_candidates', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'price_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'amount_refunded_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment_links', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('incidents', 'revenue_at_risk_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('agent_actions', 'amount_minor',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
