"""evidence graph

Revision ID: 8074e10d90fc
Revises: 282341769486
Created: 2026-09-02 00:14:19.164394
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8074e10d90fc'
down_revision = '282341769486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('predicate', sa.Enum('CAUSED_BY', 'AFFECTS', 'CREATES', 'SUPPORTED_BY', 'CONTRADICTS', name='predicate', native_enum=False), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('object_value', sa.JSON(), nullable=True),
    sa.Column('drawn_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'subject_type', 'subject_id', 'predicate', 'object_type', 'object_id', name='uq_edge_once', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_edge_subject', 'evidence_edges', ['incident_id', 'subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_evidence_edges_created_at'), 'evidence_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_edges_incident_id'), 'evidence_edges', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_edges_merchant_id'), 'evidence_edges', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_evidence_edges_predicate'), 'evidence_edges', ['predicate'], unique=False)
    op.create_index(op.f('ix_evidence_edges_tenant_id'), 'evidence_edges', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_edges_tenant_id'), table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_predicate'), table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_merchant_id'), table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_incident_id'), table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_created_at'), table_name='evidence_edges')
    op.drop_index('ix_edge_subject', table_name='evidence_edges')
    op.drop_table('evidence_edges')
    # ### end Alembic commands ###
